server:
  port: 8080
spring:
  application:
    name: rest-with-spring-boot-and-java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
   #     dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    open-in-view: false # spring.jpa.open-in-view
logging:
  level:
    root: WARN          # Configuração global (Warn é indicado para produção)
    br.com.java: DEBUG  # Configurar o nivel de log para pacotes especificos (INFO é o padrão caso nao especifique)


